# - How the lang interacts with user (I/O)
# - How the lang makes decisions (if else)
# - How the lang do repetitive tasks (loops)
# - How the lang segregates common code (functions)
# - How the language possess real life problem's properties (OOP)
# - How the language recurse (Recursion)